### ISSUE TITLE
还在报错，请帮忙看看什么原因，谢谢

### ISSUE THREAD

**Issue by ningjianghang** [HuaweiSwitch/CloudEngine-Ansible#23]
执行如下
ansible -m ce_command -a 'host=10.4.248.6 port=22 username=sankuai password=Netadmin00@mt commands="display device"' localhost --connection local 
/usr/lib/python2.6/site-packages/cryptography-2.0.3-py2.6-linux-x86_64.egg/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! Unexpected Exception: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'

**Comment by ningjianghang** [comment]
有什么解决方法吗？

**Comment by QijunPan** [comment]
从现象来看，应该是依赖库没有安装完整。建议通过在线的方式安装：
1）pip install ansible
2）pip install ncclient  
解决安装过程报的依赖错误。

另外，你的环境是python 2.6，建议在主流的python 2.7环境验证。

**Comment by QijunPan** [comment]
@ningjianghang 请提供版本信息：
1）ansible --version
2）安装的CE库是哪个分支或release？

**Comment by lingjw** [comment]
模块漏洞百出，出来也没什么意义
