### ISSUE TITLE
ce_ip_interface.py has a documentation error formatting or is missing documentation

### ISSUE THREAD

**Issue by wsf535** [HuaweiSwitch/CloudEngine-Ansible#28]
ansible-doc -l
 [ERROR]: unable to parse /usr/lib/python2.7/site-
packages/ansible-2.3.3.0-py2.7.egg/ansible/modules/network/cloudengine/ce_ip_interface.py

ERROR! module ce_ip_interface has a documentation error formatting or is missing documentation

**Comment by justbiaoliu** [comment]
Hi wsf535,
    I have fixed it, thank a lot for you comments.
Best wishes

https://github.com/HuaweiSwitch/CloudEngine-Ansible/commit/b1be6f4c93686ddaf706a45b3040e3657f6b582a
