### ISSUE TITLE
Running module on Ansible in virtualenv

### ISSUE THREAD

**Issue by shukalo83** [HuaweiSwitch/CloudEngine-Ansible#3]
Hello,

I'm trying to run the module but I get this error:
ansible all -M ./CloudEngine-Ansible/library -m ce_command -a "commands='display vlan summary' transport='cli'"

10.0.0.1 | FAILED! => {
    "failed": true,
    "msg": "The module ce_command was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem."
}

(ansible) root@debian871:~/Envs/ansible# ansible --version
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides

(ansible) root@debian871:~/Envs/ansible# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"

My other modules are in (I'm running ansible in virtualenv):
/root/Envs/ansible/lib/python2.7/site-packages/ansible/modules/

I'm running command in /root/Envs/ansible/project and here I have ansible_hosts file and also a git clone of your modules in CloudEngine-Ansible

Here's the tree command:

(ansible) root@debian871:~/Envs/ansible# tree -L 2
.
├── bin
│   ├── activate
│   ├── activate.csh
│   ├── activate.fish
│   ├── activate_this.py
│   ├── ansible
│   ├── ansible-console
│   ├── ansible-doc
│   ├── ansible-galaxy
│   ├── ansible-playbook
│   ├── ansible-pull
│   ├── ansible-vault
│   ├── easy_install
│   ├── easy_install-2.7
│   ├── get_env_details
│   ├── pip
│   ├── pip2
│   ├── pip2.7
│   ├── postactivate
│   ├── postdeactivate
│   ├── preactivate
│   ├── predeactivate
│   ├── python
│   ├── python2 -> python
│   ├── python2.7 -> python
│   ├── python-config
│   └── wheel
├── include
│   └── python2.7 -> /usr/include/python2.7
├── lib
│   └── python2.7
├── local
│   ├── bin -> /root/Envs/ansible/bin
│   ├── include -> /root/Envs/ansible/include
│   └── lib -> /root/Envs/ansible/lib
├── pip-selfcheck.json
└── project
    ├── ansible_hosts
    └── CloudEngine-Ansible

And requirments
(ansible) root@debian871:~/Envs/ansible# pip freeze
ansible==2.2.1.0
appdirs==1.4.0
cffi==1.9.1
cryptography==1.7.2
enum34==1.1.6
idna==2.2
ipaddress==1.0.18
Jinja2==2.8.1
lxml==3.7.2
MarkupSafe==0.23
ncclient==0.5.3
packaging==16.8
paramiko==2.1.1
pyasn1==0.1.9
pycparser==2.17
pycrypto==2.6.1
pyparsing==2.1.10
PyYAML==3.12
six==1.10.0
(ansible) root@debian871:~/Envs/ansible#

Thank you!

**Comment by shukalo83** [comment]
Solved. It was an issue of path to the module.

**Comment by QijunPan** [comment]
Thank you!
