### ISSUE TITLE
Cant use these modules to configure switch

### ISSUE THREAD

**Issue by ankerstal** [HuaweiSwitch/CloudEngine-Ansible#33]
Hi!

I have set up a specific account to use for configuration from ansible. But I fail to login using the module.

When I do a ssh connection manually it works just fine. But when I try with any of your modules it fails with:
```"msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"```

And the switch logs says:
```%%01SSH/5/SSH_USER_LOGIN_FAIL(s):CID=0x80932722;The SSH user failed to login. (ServiceType=**, FailedReason=TCP disconnect from client, UserName=Could not extract user name, IPAddress=172.18.10.10, VPNInstanceName=MGMT.)```

**Comment by justbiaoliu** [comment]
Hello, Ankerstal
    Many people put forward this question in ansible community, since ansible has solved it, most of them are environmental problems(e.g. configuration on the switch, configuration on the host/VM, etc.).

    Investigation can take up in this way. 
    1. Could you tell me the ansible version? Because it may exist before ansible version 2.4.2.
        a. Just run command "ansible --version"
        b.  check ce.py
       vi /usr/lib/python2.7/site-packages/ansible-2.4.2.0-py2.7.egg/ansible/plugins/action/ce.py
       I have already update it on master version.

    2. double check the host/VM could connect the cloudengine switch by ssh -p {port} {ip}
    3. double check the switch configuration whether customer has configured ssh  and netconf.
#                                                                               
aaa                                                                             
 undo local-user policy security-enhance                                        
 local-user client001 password irreversible-cipher Admin@123                                                   
 local-user client001 service-type ssh                                          
 local-user client001 level 3
#                                                                               
stelnet ipv4 server enable                                                      
snetconf ipv4 server enable                                                     
stelnet ipv6 server enable                                                      
snetconf ipv6 server enable                                                     
ssh user client001                                                              
ssh user client001 authentication-type password                                 
ssh user client001 service-type all
     4. set command "export ANSIBLE_HOST_KEY_CHECKING=false"
ansible/ansible#27136
export ANSIBLE_HOST_KEY_CHECKING=false
    5. If the issue still could not be solved, could you share you desktop?

**Comment by ankerstal** [comment]
Hi!

I installed the latest version of ansible and now it works fine. Sorry about that!

**Comment by justbiaoliu** [comment]
Glad to hear that.
