### ISSUE TITLE
missing hybrid mode in ce_switchport

### ISSUE THREAD

**Issue by scarleo** [HuaweiSwitch/CloudEngine-Ansible#38]
hybrid mode is missing from ce_switchport, only trunk and access mode is possible to configure.

**Comment by justbiaoliu** [comment]
OK, we will raise a requirement to satisfy it.

**Comment by TiDjY35** [comment]
always missing ?

**Comment by scarleo** [comment]
Yes it is still missing

**Comment by yuandongxx** [comment]
Pay a attention to ansible-2.9 which will come out next season, please.
ansible/ansible#59332

**Comment by hwDCN** [comment]
ansible/ansible#59332
