### ISSUE TITLE
Can not connect to CloudEngine switch

### ISSUE THREAD

**Issue by shukalo83** [HuaweiSwitch/CloudEngine-Ansible#4]
Hello,
This is a test environment so please disregard 'running as root' stuff...

Here are the basic facts:
(ansible) root@debian871:~/Envs/ansible/project# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"

(ansible) root@debian871:~# pip freeze
ansible==2.2.1.0
appdirs==1.4.0
cffi==1.9.1
cryptography==1.7.2
enum34==1.1.6
idna==2.2
ipaddress==1.0.18
Jinja2==2.8.1
lxml==3.7.2
MarkupSafe==0.23
ncclient==0.5.3
packaging==16.8
paramiko==2.1.1
pyasn1==0.1.9
pycparser==2.17
pycrypto==2.6.1
pyparsing==2.1.10
PyYAML==3.12
six==1.10.0

(ansible) root@debian871:~/Envs/ansible/project# cat ansible.cfg
[defaults]
remote_user = ansible
private_key_file=/root/.ssh/id_rsa
host_key_checking=False

This is my test.yml

- hosts: all
  gather_facts: False
  tasks:
    - name: Get VLANs
      ce_command: command='display vlan brief' transport='cli'

Using module file /root/Envs/ansible/local/lib/python2.7/site-packages/ansible/modules/extras/network/huawei/ce_command.py
<10.197.255.41> ESTABLISH SSH CONNECTION FOR USER: ansible
<10.197.255.41> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/root/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.197.255.41 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1487018853.48-126438048573282 `" && echo ansible-tmp-1487018853.48-126438048573282="` echo ~/.ansible/tmp/ansible-tmp-1487018853.48-126438048573282 `" ) && sleep 0'"'"''
fatal: [10.197.255.41]: UNREACHABLE! => {

ssh works manually but if I omit the '/bin/sh...' part:

So this works:
ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/root/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.197.255.41

Any help appreciated.

**Comment by numone213** [comment]
hi, I have some suggestions:
1. commands='display vlan brief'   , not command;
2. please check the configuration on the CloudEngine switch, input the command "dis cur | inc authentication-type", check if  the configuration "ssh user ansible authentication-type password" exist.

**Comment by shukalo83** [comment]
Thank you.

I've corrected the mistake with 'show vlan brief'. It's now 'show vlan'.
I don't user password here. There's a path to a private key file in my cfg file and the authentication works.  

As I said, this command works perfectly if I do it manually:

ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/root/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 10.197.255.41

The only thing that anslibe does which does not work is this part:

'/bin/sh -c '"'"'( umask 77 && mkdir -p "echo ~/.ansible/tmp/ansible-tmp-1487018853.48-126438048573282" && echo ansible-tmp-1487018853.48-126438048573282="echo ~/.ansible/tmp/ansible-tmp-1487018853.48-126438048573282" ) && sleep 0'"'"''

Does anyone know why is this happening? Why does ansible trys to create these tmp files on the host?

Bojan

**Comment by shukalo83** [comment]
I've had an instruction on stackoverflow.com not to use actual Huawei host but instead to use localhost like this:
ansible -vvv -m ce_command -a 'host="10.17.255.41" port="22" username="bojan" password="VeryStrongPass@12#$" commands="display device"' localhost --connection local

Even like that I could not connect.
Here's the log:
https://dl.dropboxusercontent.com/u/7886102/ansible_cloudengine.log

**Comment by QijunPan** [comment]
1、Does anyone know why is this happening? Why does ansible trys to create these tmp files on the host?
----  Sorry, this is the flow of Ansible fragment, I do not clear.

2、Even like that I could not connect.
Here's the log:
https://dl.dropboxusercontent.com/u/7886102/ansible_cloudengine.log
----  Sorry, I can not open the link, I think you can send email to me.
Can you show the ansible version on your test host ? Our module only support ansible 2.2 now.

**Comment by shukalo83** [comment]
Hello, even though I wrote in myu question that I had ansible 2.2 at first, later I switch to dev branch (2.3).

When I got back to 2.2 everything seems to be working now!

Thank you!

Bojan
