### ISSUE TITLE
Fail when use ce_interface.py to configure L3 interface on CE switch

### ISSUE THREAD

**Issue by ijustQqh** [HuaweiSwitch/CloudEngine-Ansible#40]
Fail when use ce_interface.py to configure L3 interface on CE switch:

 "msg": "Error: The interface 10GE1/0/1 already exists

**Comment by ijustQqh** [comment]
![image](https://user-images.githubusercontent.com/39176413/39902067-fdaad956-5506-11e8-9630-bb4c4d641151.png)


in ce_interface.py , create should be merge:
![image](https://user-images.githubusercontent.com/39176413/39902076-0a64a1d6-5507-11e8-8746-bf867004efbd.png)

**Comment by kpostrup** [comment]
I am experiencing the same problem.

**Comment by kpostrup** [comment]
Please reply.

This is a really annoying issue, making ce_interface almost unusable. And there is a very simple fix.

**Comment by yuandongxx** [comment]
ansible/ansible#58552
please pay a attention.
Thanks!
