### ISSUE TITLE
follow the example,but failed

### ISSUE THREAD

**Issue by mazengxie** [HuaweiSwitch/CloudEngine-Ansible#45]
[root@172e38e211e79 ~]# ansible -m ce_command -a "commands='display vlan summary' transport='cli' host=172.18.215.4 port=22 username=ironic password=agr&4CBG#76" localhost --connection local
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: string indices must be integers, not str
localhost | FAILED! => {
"changed": false, 
"failed": true, 
"module_stderr": "Traceback (most recent call last):\n File \"/tmp/ansible_oniuZU/ansible_module_ce_command.py\", line 269, in <module>\n main()\n File \"/tmp/ansible_oniuZU/ansible_module_ce_command.py\", line 204, in main\n supports_check_mode=True)\n File \"/tmp/ansible_oniuZU/ansible_modlib.zip/ansible/module_utils/network.py\", line 134, in __init__\n File \"/tmp/ansible_oniuZU/ansible_modlib.zip/ansible/module_utils/network.py\", line 170, in connect\n File \"/tmp/ansible_oniuZU/ansible_modlib.zip/ansible/module_utils/cloudengine.py\", line 221, in connect\n File \"/tmp/ansible_oniuZU/ansible_modlib.zip/ansible/module_utils/shell.py\", line 157, in send\nTypeError: string indices must be integers, not str\n", 
"module_stdout": "", 
"msg": "MODULE FAILURE", 
"rc": 0
}

**Comment by justbiaoliu** [comment]
Hi， @mazengxie 
I have test the ce_command, could you tell me some detail information?



##### SUMMARY


##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME


##### ANSIBLE VERSION

```

```

##### CONFIGURATION


##### OS / ENVIRONMENT


##### STEPS TO REPRODUCE



```yaml

```



##### EXPECTED RESULTS


##### ACTUAL RESULTS



```

```

root@NKG1000130279:/usr/huawei/ansible# ansible -m ce_command -a "commands='display vlan summary' transport='cli' host=10.78.106.33 port=22 username=huawei password=huaweiDC" localhost --connection local
[DEPRECATION WARNING]: Param 'username' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'password' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'host' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'transport' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'port' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
localhost | SUCCESS => {
    "changed": false,
    "stdout": [
        "Number of static VLAN: 1\nVLAN ID: 1 \n\nNumber of dynamic VLAN: 0\nVLAN ID: \n\nNumber of service VLAN: 31\nVLAN ID: 4064 to 4094"
    ],
    "stdout_lines": [
        [
            "Number of static VLAN: 1",
            "VLAN ID: 1 ",
            "",
            "Number of dynamic VLAN: 0",
            "VLAN ID: ",
            "",
            "Number of service VLAN: 31",
            "VLAN ID: 4064 to 4094"
        ]
    ]
}
root@NKG1000130279:/usr/huawei/ansible#
root@NKG1000130279:/usr/huawei/ansible# ansible --version
ansible 2.7.0dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.7.0.dev0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]
root@NKG1000130279:/usr/huawei/ansible#

**Comment by mazengxie** [comment]
[root@172e38e211e79 ~]# ansible --version
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

**Comment by mazengxie** [comment]
[root@172e38e211e79 ~]# ansible -m ce_command -a "commands='display vlan summary' transport='cli' host=172.18.215.4 port=22 username=ironic password=agr&4CBG#76" localhost  --connection local
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: string indices must be integers, not str
localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_zOn2nt/ansible_module_ce_command.py\", line 269, in <module>\n    main()\n  File \"/tmp/ansible_zOn2nt/ansible_module_ce_command.py\", line 204, in main\n    supports_check_mode=True)\n  File \"/tmp/ansible_zOn2nt/ansible_modlib.zip/ansible/module_utils/network.py\", line 134, in __init__\n  File \"/tmp/ansible_zOn2nt/ansible_modlib.zip/ansible/module_utils/network.py\", line 170, in connect\n  File \"/tmp/ansible_zOn2nt/ansible_modlib.zip/ansible/module_utils/cloudengine.py\", line 221, in connect\n  File \"/tmp/ansible_zOn2nt/ansible_modlib.zip/ansible/module_utils/shell.py\", line 157, in send\nTypeError: string indices must be integers, not str\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
[root@172e38e211e79 ~]# ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
[root@172e38e211e79 ~]#

**Comment by mazengxie** [comment]
I install in master branch.

**Comment by justbiaoliu** [comment]
Actually we could directly use ansible version after 2.4.2, cause we have merged cloudengine code into the ansible master version. 

If you still want to use version 2.3.0, could I take a check at your environment through some connection tools ?

**Comment by mazengxie** [comment]
It works well when I use ansible 2.4.2. 
thanks very much.

**Comment by justbiaoliu** [comment]
OK
