### ISSUE TITLE
"msg": "paramiko: The authenticity of host '10.78.106.58' can't be established.\nThe ssh-rsa key fingerprint is 58ec523de50903ca37d8c9d2870c53ed."

### ISSUE THREAD

**Issue by justbiaoliu** [HuaweiSwitch/CloudEngine-Ansible#46]
"msg": "paramiko: The authenticity of host '10.78.106.58' can't be established.\nThe ssh-rsa key fingerprint is 58ec523de50903ca37d8c9d2870c53ed."

**Comment by justbiaoliu** [comment]
I finally figured it out by checking the full log (paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG), paramiko will finish the connection if public key authentication failed, rather than keep trying password. So when using paramiko, the parameter "look_for_keys" in method "connect()" MUST be set to False

**Comment by wayneshow** [comment]
Where is the parameter "look_for_keys" in?
