### ISSUE TITLE
您好，我的ansible使用测试代码通过了，但在使用playbook时报错，我猜测的原因时模块没导入成功，请赐教

### ISSUE THREAD

**Issue by xu-wenkai** [HuaweiSwitch/CloudEngine-Ansible#50]
![default](https://user-images.githubusercontent.com/23653027/43682392-28a19d56-98a6-11e8-9e9d-55d4708072fb.png)
![default](https://user-images.githubusercontent.com/23653027/43682491-0f3762d0-98a9-11e8-8a6c-9ea106f1bcc8.png)

**Comment by jiangzhen1** [comment]
能提供一下playbook 和 hosts配置文件么

**Comment by xu-wenkai** [comment]
![default](https://user-images.githubusercontent.com/23653027/43758874-0c043c48-9a50-11e8-867e-225407b82065.png)
![default](https://user-images.githubusercontent.com/23653027/43758909-2c09d228-9a50-11e8-848d-884bcb8ed198.png)
其实我是拿h3c的交换机测试的，有没有可能是这个原因~

**Comment by jiangzhen1** [comment]
能否通过team viewer 共享一下环境么

**Comment by xu-wenkai** [comment]
我的微信18844051668

**Comment by jiangzhen1** [comment]
哪个公司？

**Comment by xu-wenkai** [comment]
解决方法，再修改一下ssh的密码，或者将新密码设置的更复杂

**Comment by jiangzhen1** [comment]
在aaa配置下加上undo local-user policy security-enhance的命令行可以解决这个问题
后续会在代码中添加对这种情况的处理

**Comment by yuandongxx** [comment]
This issues was fixed as bug on version 2.8.2 or latest version.
