### ISSUE TITLE
ce_facts failed : start tag expected, '<' not found, line 1, column 1 (line 1).

### ISSUE THREAD

**Issue by lonelyword** [HuaweiSwitch/CloudEngine-Ansible#57]
OS version: Redhat 7.4
Ansible Version: 2.7.5
Python Version: 2.7.5
ansible huawei -m ce_facts -a "gather_subset=config"

1.1.1.1 | FAILED! => {
      "changed": false,
      "msg": "Command: display version, start tag expected, '<' not found, line 1, column 1 (line 1)."

cfg_file in ce_startup have the same problem. Other modules, ce_vlan, works fine.

**Comment by lonelyword** [comment]
change python version to 3.7.2, still the same error

**Comment by yuandongx** [comment]
Due to the ansible version change, code rectification, in lib\ansible\plugins\action\action\ce.py, 'CLI_SUPPORTED_MODULES ' did not add ce_fact, resulting in this problem. Code follow-up updates will fix this problem.

**Comment by lonelyword** [comment]
ok

**Comment by kpostrup** [comment]
I'm getting the same error when trying from a playbook, using the example from:
https://docs.ansible.com/ansible/devel/modules/ce_facts_module.html#ce-facts-module

```
# Note: examples below use the following provider dict to handle
#       transport and authentication to the node.

- name: CloudEngine facts test
  hosts: cloudengine
  connection: local
  gather_facts: no
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      port: "{{ ansible_ssh_port }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: cli

  tasks:

  - name: "Gather_subset is all"
    ce_facts:
      gather_subset: all
      provider: "{{ cli }}"

  - name: "Collect only the config facts"
    ce_facts:
      gather_subset: config
      provider: "{{ cli }}"

  - name: "Do not collect hardware facts"
    ce_facts:
      gather_subset: "!hardware"
      provider: "{{ cli }}"
```

Error:
```
TASK [Gather_subset is all] **********************************************************************************************************************************
fatal: [leaf01]: FAILED! => {"changed": false, "msg": "Command: dir, start tag expected, '<' not found, line 1, column 1 (line 1)."}
```

**Comment by kpostrup** [comment]
Please re-open issue.

**Comment by yuandongx** [comment]
> Please re-open issue.
The bugs will be fixed after codes are merged into gihub.

**Comment by kpostrup** [comment]
> > Please re-open issue.
> > The bugs will be fixed after codes are merged into gihub.

Is this for me? I don't have access to re-open the issue.

**Comment by michadom** [comment]
This issue is still happening.
Regards,

**Comment by yuandongx** [comment]
Ansible-2.8.1 will be released and  you can have a try.
We have commited codes(#54750) to fix the bug.
Thank you.

**Comment by yuandongx** [comment]
@michadom  Will you please have a try with ansible-2.8.1?

**Comment by michadom** [comment]
> @michadom Will you please have a try with ansible-2.8.1?

Now it Works! I installed ansible 2.8.1 and works as expected. Thanks for fixing it and for all development that you all are doing to this project.

Regards,
