### ISSUE TITLE
关于安装ansible的疑问

### ISSUE THREAD

**Issue by Founderbn2014** [HuaweiSwitch/CloudEngine-Ansible#61]
您好，麻烦问一下，现在下载安装最新版本的ansible，是否还需要别的配置 ？是不是可以直接调用ce模块，看新版本里面有ce模块呢

**Comment by yuandongx** [comment]
是的，直接下载最新的版本就可以；
下载完成，配置一下/etc/ansible/ansible.cfg   可从该地址下载示例：https://github.com/ansible/ansible/blob/devel/examples/ansible.cfg
如果要用到netconf,可以pip install ncclinet
如有其它问题，可以随时咨询，谢谢！

**Comment by Founderbn2014** [comment]
> 是的，直接下载最新的版本就可以；
> 下载完成，配置一下/etc/ansible/ansible.cfg 可从该地址下载示例：https://github.com/ansible/ansible/blob/devel/examples/ansible.cfg
> 如果要用到netconf,可以pip install ncclinet
> 如有其它问题，可以随时咨询，谢谢！

感谢回复
