### ISSUE TITLE
network_cli - Connection plugin problem 

### ISSUE THREAD

**Issue by gerardocastaldo** [HuaweiSwitch/CloudEngine-Ansible#73]
Greetings,

I'm testing various modules and I have experiencing that only ce_command and ce_config support the network_cli plugin.

In others modules, example ce_bgp_neighbor_af, i don't understand why it uses the netconf module if I defined the provider cli.

Is possible for you to standardizing the network connection plugin and updates the documentation ?

Regards
Gerardo

**Comment by gerardocastaldo** [comment]
i attach the error and the code for the connection error in ce_bgp_neighbor_af.

  - name: "2 - Configure acl configuration and save it"
    ce_bgp_neighbor_af:
      state: absent
      vrf_name: js
      af_type: ipv4uni
      remote_address: 192.168.10.10
      nexthop_configure: local
      import_rt_policy_name: From-Core
      provider: "{{ cli }}"

TASK [2 - Configure acl configuration and save it] ***********************************************************************************
task path: /home/devnet/developer_gerry/playbook/test_cloud_engine_bgp.yml:34
<10.44.140.4> using connection plugin netconf (was local)
<10.44.140.4> ESTABLISH NETCONF SSH CONNECTION FOR USER: devnet on PORT 22 TO 10.44.140.4
The full traceback is:
Traceback (most recent call last):
  File "/home/devnet/custom_venv/bin/ansible-connection", line 104, in start
    self.connection._connect()
  File "/home/devnet/custom_venv/lib/python3.6/site-packages/ansible/plugins/connection/netconf.py", line 322, in _connect
    ssh_config=ssh_config
  File "/home/devnet/custom_venv/lib64/python3.6/site-packages/ncclient/manager.py", line 177, in connect
    return connect_ssh(*args, **kwds)
  File "/home/devnet/custom_venv/lib64/python3.6/site-packages/ncclient/manager.py", line 143, in connect_ssh
    session.connect(*args, **kwds)
  File "/home/devnet/custom_venv/lib64/python3.6/site-packages/ncclient/transport/ssh.py", line 516, in connect
    raise SSHError("Could not open connection, possibly due to unacceptable"
ncclient.transport.errors.SSHError: Could not open connection, possibly due to unacceptable SSH subsystem name.

fatal: [VMW-SW-HW-1]: FAILED! => {
    "msg": "Could not open connection, possibly due to unacceptable SSH subsystem name."
}

**Comment by yuandongxx** [comment]
Hi @gerardocastaldo ,as you know that some module use 'network_cli',some use 'netconf'.
NETCONF API is  faster and more efficient  than network_cli.But not all commands are supported by NETCONF，so it is that.
Then if you may not know which module use 'netocnf' or 'network_cli', you can use 'local', [action](https://github.com/HuaweiSwitch/CloudEngine-Ansible/blob/16709d4585e907a5abc69d1439ad579212228d99/plugins/action/ce.py#L22) can help you select.
Thanks.

**Comment by gerardocastaldo** [comment]
Hi, i'm sure that netconf is more faster and efficient than network_cli. My question is why in documentation i don't read that the connection module is netconf? if exists a documentation i think that it should is efficacious. That's all. 

Thanks

**Comment by yuandongxx** [comment]
Good idea!
Thanks, will do it.

**Comment by yuandongx** [comment]
See  https://docs.ansible.com/ansible/devel/network/user_guide/platform_ce.html?highlight=cloudengine
